version: "3.8"

services:
  db:
    image: postgres:15
    container_name: leveling_db
    environment:
      POSTGRES_USER: hunter
      POSTGRES_PASSWORD: arise
      POSTGRES_DB: system_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leveling_backend
    environment:
      DATABASE_URL: postgres://hunter:arise@db:5432/system_db
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leveling_frontend
    depends_on:
      - backend
    restart: always

  reverse-proxy:
    image: nginx:stable-alpine
    container_name: main_proxy
    ports:
      - "10.0.0.235:80:80"
      - "10.0.0.235:443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
